name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: tt10_helloworld

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@tt10
